title: Ekaterina Suprunenko # your name (or website title) here
logo: "/images/profile_photo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Recently accomplished Master's Degree in Data Science from Neural Academy (Rome, Italy).
  Aspiring Junior Data Analyst. Skilled in Python, Machine Learning, Statistics, Data Visualisation and Communication.
  <br><br>
  <a href="https://www.linkedin.com/in/ekaterina-s-1ab303154/">View my LinkedIn Profile</a>  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
colors:
  crimson: '#900C3F'
